const TABLES = {
  faturali: { title:'Faturalı Siparişler', storage:'mep_faturali', fields:['date','customer','product','qty','cost','sale','vatDiff','vatTotal','profit','status','payment','invoice','note'], samples:[{date:'2025-05-26',customer:'ABC Reklam',product:'Afiş Baskı 50x70',qty:500,cost:1250,sale:2500,vatDiff:450,status:'Üretimde',payment:'Ödendi',invoice:'K',note:'Acele'}]},
  gelen: { title:'Gelen Faturalar', storage:'mep_gelen', fields:['date','company','product','qty','total','vatTotal','vatDiff','receiveStatus','paymentSimple','note'], samples:[{date:'2025-05-26',company:'ABC Ambalaj',product:'Karton Kutu',qty:1000,total:2500,vatDiff:450,receiveStatus:'Teslim Alındı',paymentSimple:'Ödendi',note:'Malzemeler tam teslim alındı.'}]},
  faturasiz: { title:'Faturasız Siparişler', storage:'mep_faturasiz', fields:['date','customer','product','qty','cost','sale','profit','status','payment','note'], samples:[{date:'2025-05-26',customer:'ABC Reklam',product:'Afiş Baskı 50x70',qty:500,cost:1250,sale:2500,status:'Üretimde',payment:'Ödendi',note:'Tasarım onaylandı.'}]}
};
let db=null; if(window.MEP_SUPABASE_URL&&window.MEP_SUPABASE_ANON_KEY){db=supabase.createClient(window.MEP_SUPABASE_URL,window.MEP_SUPABASE_ANON_KEY)}
const money=n=>Number(n||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
const uid=()=>crypto.randomUUID();
function calc(row){const sale=Number(row.sale||0), cost=Number(row.cost||0), vat=Number(row.vatDiff||0), total=Number(row.total||0); return {profit:sale-cost, vatTotal: sale? sale+vat : total+vat}}
async function load(key){ if(db){const {data,error}=await db.from(key).select('*').order('created_at',{ascending:false}); if(!error) return data||[]} const raw=localStorage.getItem(TABLES[key].storage); return raw?JSON.parse(raw):TABLES[key].samples.map(x=>({...x,id:uid()}));}
async function saveAll(key,rows){ if(!db) localStorage.setItem(TABLES[key].storage,JSON.stringify(rows)); }
function badge(v){let c='blue'; if(['Ödendi','Teslim Edildi','Teslim Alındı','Hazır','K'].includes(v))c='green'; if(['Ödenmedi','Bekleniyor','X'].includes(v))c='red'; if(['Üretimde','Kısmi Ödeme','Hazır'].includes(v))c='orange'; if(v==='Üretimde')c='blue'; return `<span class="badge ${c}">${v||''}</span>`}
function headers(key){return {
 faturali:['Tarih','Müşteri Adı','Ürün','Adet','Toplam Maliyet','Toplam Satış','KDV Farkı','KDV Dahil Toplam','Kâr','Durumu','Ödeme Durumu','Fatura Durumu','Açıklama','İşlem'],
 gelen:['Tarih','Firma','Ürün','Adet','Toplam Tutar','KDV Dahil Toplam','KDV Farkı','Durumu','Ödeme Durumu','Açıklama / Not','İşlem'],
 faturasiz:['Tarih','Müşteri Adı','Ürün','Adet','Toplam Maliyet','Toplam Satış','Kâr','Durumu','Ödeme Durumu','Notlar','İşlem']
}[key]}
function formFields(key){return {
 faturali:[['date','Tarih','date'],['customer','Müşteri Adı'],['product','Ürün'],['qty','Adet','number'],['cost','Toplam Maliyet','number'],['sale','Toplam Satış','number'],['vatDiff','KDV Farkı','number'],['status','Durumu','select',['Üretimde','Hazır','Teslim Edildi']],['payment','Ödeme Durumu','select',['Ödendi','Bekleniyor','Kısmi Ödeme']],['invoice','Fatura Durumu','select',['K','X']],['note','Açıklama','textarea']],
 gelen:[['date','Tarih','date'],['company','Firma'],['product','Ürün'],['qty','Adet','number'],['total','Toplam Tutar','number'],['vatDiff','KDV Farkı','number'],['receiveStatus','Durumu','select',['Teslim Alındı','Üretimde']],['paymentSimple','Ödeme Durumu','select',['Ödendi','Ödenmedi']],['note','Açıklama / Not','textarea']],
 faturasiz:[['date','Tarih','date'],['customer','Müşteri Adı'],['product','Ürün'],['qty','Adet','number'],['cost','Toplam Maliyet','number'],['sale','Toplam Satış','number'],['status','Durumu','select',['Üretimde','Hazır','Teslim Edildi']],['payment','Ödeme Durumu','select',['Ödendi','Bekleniyor','Kısmi Ödeme']],['note','Notlar','textarea']]
}[key]}
function rowCells(key,row){const c=calc(row); if(key==='faturali')return [row.date,row.customer,row.product,row.qty,money(row.cost),money(row.sale),money(row.vatDiff),money(c.vatTotal),`<span class=profit>${money(c.profit)}</span>`,badge(row.status),badge(row.payment),badge(row.invoice),row.note]; if(key==='gelen')return [row.date,row.company,row.product,row.qty,money(row.total),money(c.vatTotal),money(row.vatDiff),badge(row.receiveStatus),badge(row.paymentSimple),row.note]; return [row.date,row.customer,row.product,row.qty,money(row.cost),money(row.sale),`<span class=profit>${money(c.profit)}</span>`,badge(row.status),badge(row.payment),row.note]}
function summary(key,rows){let s={cost:0,sale:0,vat:0,profit:0,total:rows.length}; rows.forEach(r=>{const c=calc(r); s.cost+=Number(r.cost||r.total||0); s.sale+=Number(r.sale||0); s.vat+=Number(r.vatDiff||0); s.profit+=c.profit}); const items= key==='gelen' ? [['Toplam Tutar',s.cost],['KDV Farkı',s.vat],['KDV Dahil Toplam',s.cost+s.vat],['Toplam Kayıt',s.total]] : [['Toplam Maliyet',s.cost],['Toplam Satış',s.sale],['Toplam Kâr',s.profit],['KDV Farkı',s.vat],['Toplam Kayıt',s.total]]; return `<div class=summary>${items.map(([a,b])=>`<div class=sum><small>${a}</small><b>${typeof b==='number'&&a!=='Toplam Kayıt'?money(b):b}</b></div>`).join('')}</div>`}
async function renderPage(key){let rows=await load(key); const el=document.querySelector('#page-'+key); const h=headers(key); el.innerHTML=`<h1 class=page-title>${TABLES[key].title}</h1><div class=toolbar><div class=left-tools><button class="btn btn-red add">+ Yeni Kayıt Ekle</button></div><div class=right-tools><button class="btn btn-light export">Excel'e Aktar</button><input class=search placeholder="Ara..."/></div></div><div class=card><table class=table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody></tbody></table></div><div class=sumwrap></div><div class=modal><div class=modal-box><h2>Yeni Kayıt</h2><div class=form-grid>${formFields(key).map(f=>fieldHtml(f)).join('')}</div><div class=modal-actions><button class="btn btn-light close">Vazgeç</button><button class="btn btn-red save">Kaydet</button></div></div></div>`; const tbody=el.querySelector('tbody'), sum=el.querySelector('.sumwrap'), search=el.querySelector('.search'); let editId=null;
 const draw=()=>{let q=search.value.toLowerCase();let list=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)); tbody.innerHTML=list.map(r=>`<tr>${rowCells(key,r).map(x=>`<td>${x??''}</td>`).join('')}<td><div class=actions><button class="iconbtn edit" data-id="${r.id}">✎</button><button class="iconbtn del" data-id="${r.id}">🗑</button></div></td></tr>`).join(''); sum.innerHTML=summary(key,rows)}; draw();
 el.querySelector('.add').onclick=()=>openModal(el,key); el.querySelector('.close').onclick=()=>closeModal(el); search.oninput=draw;
 el.querySelector('.save').onclick=async()=>{let obj=getForm(el,key); if(editId) obj.id=editId; else obj.id=uid(); if(db){ const {error}= await db.from(key).upsert(obj); if(error){alert(error.message);return} rows=await load(key);} else { rows=editId?rows.map(r=>r.id===editId?obj:r):[obj,...rows]; await saveAll(key,rows);} editId=null; closeModal(el); draw();};
 tbody.onclick=async e=>{const id=e.target.dataset.id; if(!id)return; if(e.target.classList.contains('del')){ if(!confirm('Kayıt silinsin mi?'))return; if(db) await db.from(key).delete().eq('id',id); rows=rows.filter(r=>r.id!==id); await saveAll(key,rows); draw(); } if(e.target.classList.contains('edit')){ editId=id; openModal(el,key,rows.find(r=>r.id===id)); }};
 el.querySelector('.export').onclick=()=>exportCsv(key,rows);
}
function fieldHtml(f){const [name,label,type='text',opts]=f; if(type==='select')return `<div class=field><label>${label}</label><select name=${name}>${opts.map(o=>`<option>${o}</option>`).join('')}</select></div>`; if(type==='textarea')return `<div class=field><label>${label}</label><textarea name=${name}></textarea></div>`; return `<div class=field><label>${label}</label><input name=${name} type=${type} /></div>`}
function openModal(el,key,row={}){el.querySelector('.modal').classList.add('active'); formFields(key).forEach(([n,,t])=>{let input=el.querySelector(`[name=${n}]`); input.value=row[n]??(t==='date'?new Date().toISOString().slice(0,10):'')})}
function closeModal(el){el.querySelector('.modal').classList.remove('active')}
function getForm(el,key){let obj={}; formFields(key).forEach(([n,,t])=>{let v=el.querySelector(`[name=${n}]`).value; obj[n]=t==='number'?Number(v||0):v}); const c=calc(obj); obj.profit=c.profit; obj.vatTotal=c.vatTotal; return obj}
function exportCsv(key,rows){const csv=[headers(key).slice(0,-1).join(';'),...rows.map(r=>rowCells(key,r).map(x=>String(x).replace(/<[^>]+>/g,'')).join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob(['\ufeff'+csv])); a.download=TABLES[key].title+'.csv'; a.click();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active')); b.classList.add('active'); document.querySelector('#page-'+b.dataset.page).classList.add('active')});
Object.keys(TABLES).forEach(renderPage);
